### ISSUE TITLE
radia-run for interactive docker should cd home

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#10]
```text
yeah that works. Bit still when I run python /vagrant/plot.py I get:

[2.7.10; /]$ touch /vagrant/foo
[2.7.10; /]$ python /vagrant/plot.py
# Warp
# Origin date: Fri, 5 Feb 2016 13:18:35 -0800
# Local date: Fri, 5 Feb 2016 13:18:35 -0800
# Commit hash: c629b89
# /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/warp/warp.pyc
# /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/warp/warpC.so
# Wed Mar  2 18:50:43 2016
# import warp time 0.101321935654 seconds
# For more help, type warphelp()
Plot file name plot.000.cgm
Traceback (most recent call last):
  File "/vagrant/plot.py", line 5, in <module>


    setup()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/warp/diagnostics/warpplots.py", line 277, in setup
    cgmlogfile = open(plogname,"w")
IOError: [Errno 13] Permission denied: 'plot.000.cgmlog'
```

**Comment by robnagler** [comment]
Fixed with 6c5aecad1c25d0bf9f74913c5544cea33a339159
