### ISSUE TITLE
warp failing with undefined symbol mpi_comm_rank_

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#12]
beamsim container build is failing with warp import failure:

```python
>>> import warp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/warp/__init__.py", line 1, in <module>
    from .warp import *
  File "/usr/lib64/python2.7/site-packages/warp/warp.py", line 114, in <module>
    from . import warpC
ImportError: /usr/lib64/python2.7/site-packages/warp/warpC.so: undefined symbol: mpi_comm_rank_
>>>

**Comment by robnagler** [comment]
Real fix pending on fix by Warp team to [bitbucket.com/berkeleylab/warp#5](https://bitbucket.org/berkeleylab/warp/issues/5/latest-builds-not-linking-properly)
