### ISSUE TITLE
f32 report_test warppba beamPreviewReport core dump

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#141]
```txt
$ python parameters.py
# Warp
# Origin date: Wed, 29 Jul 2020 23:25:38 -0600
# Local date: Wed, 29 Jul 2020 23:25:38 -0600
# Commit hash: c2d91f0
# /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/warp.py
# /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/warpC.cpython-37m-x86_64-linux-gnu.so
# Wed Dec 30 18:12:48 2020
# import warp time 0.1850438117980957 seconds
# For more help, type warphelp()
('l_fftw_fort', False)
 ***  particle simulation package W3D generating
 ---  Resetting lattice array sizes
 ---  Allocating space for particles
 ---  Loading particles
 ---  Setting charge density
 ---  done
 ---  Allocating Win_Moments
 ---  Allocating Z_Moments
 ---  Allocating Lab_Moments
it =      0 time = 0.0000E+00 pz = 0.0000E+00 ese = 0.0000E+00 ek = 0.0000E+00 et = 0.0000E+00
alphax,alphaz,betazx,betaxz 0.859375 0.75 0.125 0.07031249999999999
alphax,alphaz,betazx,betaxz 0.859375 0.75 0.125 0.07031249999999999
free(): invalid pointer
Aborted (core dumped)
```

```txt
#0  0x00007ffff79839e5 in raise () from /lib64/libc.so.6
#1  0x00007ffff796c895 in abort () from /lib64/libc.so.6
#2  0x00007ffff79c7857 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff79ced7c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff79cff44 in _int_free () from /lib64/libc.so.6
#5  0x00007fffe886341c in restrict2d_ () from /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp/f3dpy.cpython-37m-x86_64-linux-gnu.so
#6  0x00007fffe886ef7d in vcycle2d_ () from /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp/f3dpy.cpython-37m-x86_64-linux-gnu.so
#7  0x00007fffe888d263 in multigrid2dsolve_ () from /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp/f3dpy.cpython-37m-x86_64-linux-gnu.so
#8  0x00007fffe87d4a6b in f3d_multigrid2dsolve (self=<optimized out>, args=<optimized out>)
    at /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1483
#9  0x00007ffff7d261b9 in _PyMethodDef_RawFastCallKeywords (method=<optimized out>, self=<optimized out>, args=<optimized out>, nargs=33, kwnames=0x0) at Objects/call.c:694
#10 0x00007ffff7d26278 in _PyCFunction_FastCallKeywords (func=0x7fffe8befb88, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:730
#11 0x00007ffff7cfbc4b in call_function (pp_stack=pp_stack@entry=0x7fffffffcd00, oparg=oparg@entry=33, kwnames=kwnames@entry=0x0) at Python/ceval.c:4568
#12 0x00007ffff7cff613 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#13 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe80a91e0, globals=globals@entry=0x7fffe8091288, locals=locals@entry=0x0, args=<optimized out>, argcount=6,
    kwnames=0x0, kwargs=0x7fffd818bdb8, kwcount=0, kwstep=1, defs=0x7fffe80a4428, defcount=5, kwdefs=0x0, closure=0x0, name=0x7fffe80a0fa8, qualname=0x7fffe80a6800) at Python/ceval.c:3930
#14 0x00007ffff7d25cab in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#15 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffcfb8, oparg=oparg@entry=6, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#16 0x00007ffff7cfcb44 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#17 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe80a2db0, globals=globals@entry=0x7fffe8091288, locals=locals@entry=0x0, args=<optimized out>, argcount=6,
    kwnames=0x0, kwargs=0x7fffd818bbc8, kwcount=0, kwstep=1, defs=0x7fffe80a43d0, defcount=5, kwdefs=0x0, closure=0x0, name=0x7fffe8284c00, qualname=0x7fffe80aa030) at Python/ceval.c:3930
#18 0x00007ffff7d25cab in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#19 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffd278, oparg=oparg@entry=6, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#20 0x00007ffff7cfcb44 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#21 0x00007ffff7cfa783 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=6, globals=<optimized out>) at Objects/call.c:283
#22 0x00007ffff7d25dcf in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:415
#23 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffd438, oparg=oparg@entry=6, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#24 0x00007ffff7cfcb44 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#25 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe820d300, globals=globals@entry=0x7fffe8274510, locals=locals@entry=0x0, args=<optimized out>, argcount=1,
    kwnames=0x7fffe806dae0, kwargs=0x9512c0, kwcount=2, kwstep=1, defs=0x7fffe8210460, defcount=2, kwdefs=0x0, closure=0x0, name=0x7fffec4fc500, qualname=0x7fffe8282d50)
    at Python/ceval.c:3930
#26 0x00007ffff7d25cab in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#27 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffd708, oparg=oparg@entry=2, kwnames=kwnames@entry=0x7fffe806dac8) at Python/ceval.c:4616
#28 0x00007ffff7d00977 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3139
#29 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe806c5d0, globals=globals@entry=0x7fffe8091e10, locals=locals@entry=0x0, args=<optimized out>, argcount=1,
    kwnames=0x7fffd7af0408, kwargs=0x9865b8, kwcount=3, kwstep=1, defs=0x7fffe806e7f8, defcount=3, kwdefs=0x0, closure=0x0, name=0x7fffe806e300, qualname=0x7fffe806e348)
    at Python/ceval.c:3930
#30 0x00007ffff7d25cab in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#31 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffd9c8, oparg=oparg@entry=3, kwnames=kwnames@entry=0x7fffd7af03f0) at Python/ceval.c:4616
#32 0x00007ffff7d00977 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3139
#33 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7fffe69deae0, globals=globals@entry=0x7fffe7e7b288, locals=locals@entry=0x0, args=<optimized out>, argcount=5,
    kwnames=0x0, kwargs=0x46e350, kwcount=0, kwstep=1, defs=0x7fffe7e7d320, defcount=2, kwdefs=0x0, closure=0x0, name=0x7ffff7467b28, qualname=0x7ffff7467b28) at Python/ceval.c:3930
#34 0x00007ffff7d25cab in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#35 0x00007ffff7cfba05 in call_function (pp_stack=pp_stack@entry=0x7fffffffdc80, oparg=oparg@entry=5, kwnames=kwnames@entry=0x0) at Python/ceval.c:4616
#36 0x00007ffff7cff613 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#37 0x00007ffff7dee84a in _PyEval_EvalCodeWithName (_co=_co@entry=0x7ffff7500930, globals=globals@entry=0x7ffff7575168, locals=locals@entry=0x7ffff7575168, args=args@entry=0x0,
    argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#38 0x00007ffff7deeace in PyEval_EvalCodeEx (_co=_co@entry=0x7ffff7500930, globals=globals@entry=0x7ffff7575168, locals=locals@entry=0x7ffff7575168, args=args@entry=0x0,
    argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3959
#39 0x00007ffff7deeafb in PyEval_EvalCode (co=co@entry=0x7ffff7500930, globals=globals@entry=0x7ffff7575168, locals=locals@entry=0x7ffff7575168) at Python/ceval.c:524
#40 0x00007ffff7e1efc1 in run_mod (arena=0x7ffff766f0a8, flags=0x7fffffffdf5c, locals=0x7ffff7575168, globals=0x7ffff7575168, filename=0x7ffff746bc70, mod=0x4ccec0)
    at Python/pythonrun.c:1035
#41 PyRun_FileExFlags (fp=fp@entry=0x405310, filename_str=filename_str@entry=0x7ffff74d9c50 "parameters.py", start=start@entry=257, globals=globals@entry=0x7ffff7575168,
    locals=locals@entry=0x7ffff7575168, closeit=closeit@entry=1, flags=0x7fffffffdf5c) at Python/pythonrun.c:988
#42 0x00007ffff7e1f14b in PyRun_SimpleFileExFlags (fp=fp@entry=0x405310, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdf5c) at Python/pythonrun.c:429
#43 0x00007ffff7e1f5fc in PyRun_AnyFileExFlags (fp=fp@entry=0x405310, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffffffdf5c) at Python/pythonrun.c:84
#44 0x00007ffff7e3e757 in pymain_run_file (p_cf=0x7fffffffdf5c, filename=<optimized out>, fp=0x405310) at Modules/main.c:427
#45 pymain_run_filename (cf=0x7fffffffdf5c, pymain=0x7fffffffe030) at Modules/main.c:1627
#46 pymain_run_python (pymain=0x7fffffffe030) at Modules/main.c:2876
#47 pymain_main (pymain=pymain@entry=0x7fffffffe030) at Modules/main.c:3037
#48 0x00007ffff7e3e989 in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:3072
#49 0x00007ffff796e042 in __libc_start_main () from /lib64/libc.so.6
#50 0x000000000040107e in _start ()
```

**Comment by robnagler** [comment]
This is caused by a change in Warp. [c2d91f02](https://bitbucket.org/radiasoft/warp/commits/c2d91f021a3b07096d363044b9aa14a1488bb094) causes this, but the commit in use on f29 [4ebb54f2](https://bitbucket.org/radiasoft/warp/commits/4ebb54f21373d41b8b1abe2f7a6011896324907f) does not cause this.

**Comment by robnagler** [comment]
FTR, the file that gets the error is: [parameters-py.txt](https://github.com/radiasoft/download/files/5755680/parameters-py.txt)
