### ISSUE TITLE
pymesh unit tests fail

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#253]
```txt
Successfully built pymesh2
Installing collected packages: pymesh2
Successfully installed pymesh2-0.3
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/home/vagrant/.pyenv/versions/3.10.5/envs/py3/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/numpy/testing/_private/nosetester.py", line 461, in test
    t = NumpyTestProgram(argv=argv, exit=False, plugins=plugins)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/vagrant/.pyenv/versions/3.10.5/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/loader.py", line 329, in loadTestsFromModule
    elif isfunction(test) and self.selector.wantFunction(test):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/selector.py", line 149, in wantFunction
Running unit tests for pymesh
NumPy version 1.22.4
NumPy relaxed strides checking option: True
NumPy is installed in /home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/numpy
Python version 3.10.5 (main, Jun 14 2022, 03:30:43) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
nose version 1.3.7
    plug_wants = self.plugins.wantFunction(function)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/plugins/attrib.py", line 278, in wantFunction
    return self.validateAttrib(function)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.10/site-packages/nose/plugins/attrib.py", line 242, in validateAttrib
    if isinstance(value, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by e-carlin** [comment]
Didn't happen for me
