### ISSUE TITLE
shadow3   AttributeError: build_src

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#255]
```txt
     running build_clib
      running build_src
      INFO: customize UnixCCompiler
      INFO: customize UnixCCompiler using BuildClib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/var/tmp/radia-run-242-12100/pip-install-9tnl3m0o/shadow3_d57818bc3b2c4948baf0b93783ae2f47/setup.py", line 103, in <module>
          setup(
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/numpy/distutils/command/build_clib.py", line 122, in run
          dispatch_hpath = os.path.join(self.get_finalized_command("build_src").build_src, dispatch_hpath)
        File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: build_src
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shadow3

```

**Comment by robnagler** [comment]
pyproject.toml
