### ISSUE TITLE
mantid build failed on build server

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#286]
```
curl -L -s -S https://api.github.com/repos/radiasoft/download/contents/installers/rpm-code/codes/mantid/rsmantid.sh
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/ipykernel/connect.py", line 10, in <module>
    from ipython_genutils.path import filefind
ModuleNotFoundError: No module named 'ipython_genutils'
```

I know I solved this already. Need to remember the solution...

**Comment by e-carlin** [comment]
ipykernel dropped support for ipython_genutils in 6.5.0. Need to rebuld.
