### ISSUE TITLE
f36 import mantid fails

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#467]
```
CMake (main)$ rsmantid -c 'from mantid import simpleapi'
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/mantid/lib/mantid/utils/_utils.py", line 37, in import_mantid_cext
    lib = import_module(modulename, package)
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/vagrant/.local/lib/mantid/lib/mantid/api/../../../lib/libMantidGeometry.so: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/mantid/lib/mantid/utils/_utils.py", line 41, in import_mantid_cext
    lib = import_module(modulename.lstrip('.'))
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.local/lib/mantid/lib/mantid/__init__.py", line 109, in <module>
    from mantid import api as _api  # noqa: F401, E402
  File "/home/vagrant/.local/lib/mantid/lib/mantid/api/__init__.py", line 20, in <module>
    import_mantid_cext('._api', 'mantid.api', globals())
  File "/home/vagrant/.local/lib/mantid/lib/mantid/utils/_utils.py", line 46, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._api" failed with "/home/vagrant/.local/lib/mantid/lib/mantid/api/../../../lib/libMantidGeometry.so: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv". Second import of "_api" failed with "No module named '_api'"
```

I believe that error [comes from opencascade](https://forum.freecad.org/viewtopic.php?style=5&t=68128). Opencascade was added when we upgraded to f36 (and upgraded mantid versions). It has also caused problems by increasing the size of the beamsim image by 3gb. It is unclear to me, at the moment, what exactly opencascade is used for. But, my best guess is 3d visualization. Since we don't do any visualization with mantid (we just use the python api) I think it might be safe to remove it. There is a cmake option [to disable it](https://github.com/mantidproject/mantid/blob/v6.4.0/buildconfig/CMake/CommonSetup.cmake#L59) which I'll try.

**Comment by e-carlin** [comment]
I removed the values but the build hangs

`[427/1897] Building CXX object Framework/PythonInterface/mantid/geometry/CMakeFiles/PythonGeometryModule.dir/src/Exports/MeshObject.cpp.o`

```
vagrant     3667  0.0  0.0   4864  2944 ?        S    11:55   0:00 /usr/bin/c++ -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_BIND_GLOBAL_PLACEHOLDERS -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DH5_BUILT_AS_DYNAMIC_LIB -DHAVE_STDINT_H -DIN_MANTID_KERNEL -DKernel_\
EXPORTS -DPOCO_ENABLE_CPP11 -DPSAPI_VERSION=1 -D_SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/Framework/Kernel/inc -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/ma\
ntid/build/Framework/Kernel -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/Framework/Types/inc -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/Framework/Types -I/home/vagrant/src/radiasoft/codes/mantid-20230424\
.114938/code/mantid/Framework/Json/inc -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/Framework/Json -I/home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/_deps/span-src/include -isystem /usr/include/mpich-x86_\
64 -isystem /home/vagrant/.local/include -isystem /home/vagrant/.local/include/nexus -isystem /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/_deps/eigen-src -O3 -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -Wall -Wextra -Wconversion\
 -Winit-self -Wpointer-arith -Wcast-qual -Wcast-align -fno-common -Wno-deprecated -Wno-write-strings -Wno-unused-result -Woverloaded-virtual -fno-operator-names -Wpedantic -Wsuggest-override -Wimplicit-fallthrough=0 -fdiagnostics-color=always -fopenmp -MD -MT Fra\
mework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.o -MF Framework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.o.d -o Framework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.o -c /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/Framework/Kernel/src/At\
om.cpp
vagrant     3668 95.5  9.4 791872 769116 ?       R    11:55  67:11 /usr/libexec/gcc/x86_64-redhat-linux/12/cc1plus -quiet -I /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/Framework/Kernel/inc -I /home/vagrant/src/radiasoft/codes/mantid-2023\
0424.114938/code/mantid/build/Framework/Kernel -I /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/Framework/Types/inc -I /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/Framework/Types -I /home/vagrant/src/radiasoft\
/codes/mantid-20230424.114938/code/mantid/Framework/Json/inc -I /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/Framework/Json -I /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/_deps/span-src/include -MD Fram\
ework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.d -MF Framework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.o.d -MT Framework/Kernel/CMakeFiles/Kernel.dir/src/Atom.cpp.o -D_GNU_SOURCE -D_REENTRANT -D BOOST_ALL_DYN_LINK -D BOOST_ALL_NO_LIB -D BOOST_BIND_GLOBAL_PLACE\
HOLDERS -D BOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -D H5_BUILT_AS_DYNAMIC_LIB -D HAVE_STDINT_H -D IN_MANTID_KERNEL -D Kernel_EXPORTS -D POCO_ENABLE_CPP11 -D PSAPI_VERSION=1 -D _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING -D NDEBUG -isystem /usr/include/\
mpich-x86_64 -isystem /home/vagrant/.local/include -isystem /home/vagrant/.local/include/nexus -isystem /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid/build/_deps/eigen-src /home/vagrant/src/radiasoft/codes/mantid-20230424.114938/code/mantid\
/Framework/Kernel/src/Atom.cpp -quiet -dumpdir Framework/Kernel/CMakeFiles/Kernel.dir/src/ -dumpbase Atom.cpp.cpp -dumpbase-ext .cpp -mtune=generic -march=x86-64 -O3 -Wall -Wextra -Wconversion -Winit-self -Wpointer-arith -Wcast-qual -Wcast-align -Wno-deprecated -\
Wno-write-strings -Wno-unused-result -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wimplicit-fallthrough=0 -std=gnu++17 -fdiagnostics-color=always -fPIC -fvisibility=hidden -fno-common -fno-operator-names -fopenmp -o /var/tmp/radia-run-218-28114/ccwG8Sbd.s
```

I tried changing to a serial build (no -j) and I tried switching to ninja instead of Makefiles because that is what they use to build conda so I figured it was more tested. Still hangs. 

I'll try building on my machine instead of in docker and see if I can strace and figure out what's going on.
