### ISSUE TITLE
AttributeError: module '_xraylib' has no attribute 'F1_TRANS'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#546]
```txt
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 33, in <module>
    sys.exit(load_entry_point('sirepo', 'console_scripts', 'sirepo')())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/pykern/pkcli/__init__.py", line 158, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 183, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 294, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 277, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/shadow.py", line 55, in run
    res = _run_beam_statistics(cfg_dir, data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/shadow.py", line 87, in _run_beam_statistics
    template_common.exec_parameters()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 377, in exec_parameters
    return pkrunpy.run_path_as_module(path or PARAMETERS_PYTHON_FILE)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/pykern/pkrunpy.py", line 28, in run_path_as_module
    exec(code, m.__dict__)
  File "parameters.py", line 2, in <module>
    from Shadow.ShadowPreprocessorsXraylib import prerefl, pre_mlayer, bragg
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/Shadow/__init__.py", line 26, in <module>
    import Shadow.ShadowPreprocessorsXraylib as ShadowPreprocessorsXraylib
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/Shadow/ShadowPreprocessorsXraylib.py", line 30, in <module>
    import xraylib
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/xraylib.py", line 3701, in <module>
    F1_TRANS = _xraylib.F1_TRANS
AttributeError: module '_xraylib' has no attribute 'F1_TRANS'
```

**Comment by robnagler** [comment]
Two _xraylib xraylib:
1. rscode-bluesky: _xraylib.cpython-39-x86_64-linux-gnu.so
2. rscode-xraylib: _xraylib.so

`xraylib` python module finds the first one but needs the second. bluesky is using pip to install 4.1.3 and xraylib.sh is using make to install xraylib.py 3.2.0.
