### ISSUE TITLE
pin traitlets

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#551]
https://github.com/jupyter/notebook/issues/7048

This happened while running jupyterhub in dev
```
HTTP/1.1" 200 4286 "http://127.0.0.1:8080/jupyter/hub/spawn-pending/vagrant" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/traitlets/traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import main
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/jupyterhub/singleuser/app.py", line 18, in <module>
    SingleUserNotebookApp = make_singleuser_app(App)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 803, in make_singleuser_app
    empty_parent_app = App()
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/traitlets/traitlets.py", line 1295, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/traitlets/traitlets.py", line 1338, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/traitlets/traitlets.py", line 1314, in setup_instance
    init(self)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/notebook/traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/notebook/traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
Task exception was never retrieved
```

**Comment by e-carlin** [comment]
pipdeptree reports notebook is required by rsflash. But dnf doesn't report that file being owned by rsbeams (which installs rsflash). Not sure wondering what's going on. But, I think we might just want to pin notebook to >6.5.6 (and rebuild whatever code contains it) rather than constrain traitlets to a lower version.

**Comment by robnagler** [comment]
Fix e002842
