### ISSUE TITLE
jupyterlab not loading

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#91]
Think I ran into this https://github.com/jupyterhub/the-littlest-jupyterhub/issues/211 but doesn't explain this:

```txt
GET https://alpha-jupyter.radiasoft.org/hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2 net::ERR_ABORTED 404 (Not Found)
lab:11 GET https://alpha-jupyter.radiasoft.org/hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=9df10041c3e07da766e7c48dd4c35e4a net::ERR_ABORTED 404 (Not Found)
lab:25 GET https://alpha-jupyter.radiasoft.org/hub/custom/custom.css net::ERR_ABORTED 404 (Not Found)
lab:16 GET https://alpha-jupyter.radiasoft.org/hub/static/style/style.min.css?v=2165fc0d023f0baf5cce3b2a6db40e22 net::ERR_ABORTED 404 (Not Found)
lab:26 GET https://alpha-jupyter.radiasoft.org/hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe net::ERR_ABORTED 404 (Not Found)
lab:27 GET https://alpha-jupyter.radiasoft.org/hub/static/components/react/react.production.min.js?v=34f96ffc962a7deecc83037ccb582b58 net::ERR_ABORTED 404 (Not Found)
lab:29 GET https://alpha-jupyter.radiasoft.org/hub/static/components/create-react-class/index.js?v=94feb9971ce6d26211729abc43f96cd2 net::ERR_ABORTED 404 (Not Found)
lab:132 GET https://alpha-jupyter.radiasoft.org/hub/static/base/images/logo.png?v=641991992878ee24c6f3826e81054a0f 404 (Not Found)
lab:28 GET https://alpha-jupyter.radiasoft.org/hub/static/components/react/react-dom.production.min.js?v=b14d91fb641317cda38dbc9dbf985ab4 net::ERR_ABORTED 404 (Not Found)
lab:29 GET https://alpha-jupyter.radiasoft.org/hub/static/components/create-react-class/index.js?v=94feb9971ce6d26211729abc43f96cd2 net::ERR_ABORTED 404 (Not Found)
require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1961 GET https://alpha-jupyter.radiasoft.org/hub/static/components/jquery/jquery.min.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1961
load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1685
load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:834
fetch @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:824
check @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:856
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1176
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1557
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1161
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:134
each @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:59
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1113
init @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:788
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1460
setTimeout (async)
req.nextTick @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1815
localRequire @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1449
requirejs @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1797
(anonymous) @ lab:174
require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168 Uncaught Error: Script error for "jquery"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168)
    at HTMLScriptElement.onScriptError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1738)
makeError @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
onScriptError @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1738
error (async)
req.load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1943
load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1685
load @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:834
fetch @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:824
check @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:856
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1176
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1557
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1161
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:134
each @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:59
enable @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1113
init @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:788
(anonymous) @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1460
setTimeout (async)
req.nextTick @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1815
localRequire @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1449
requirejs @ require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1797
(anonymous) @ lab:174
```

**Comment by robnagler** [comment]
Ha ha  I found this: https://github.com/jupyterlab/jupyterlab/issues/7067 Which I reported in Aug. It does not fix the issue, because labhub isn't there.

**Comment by robnagler** [comment]
I have been chasing a variety of bugs all day. Tried the-littlest-jupyterhub and it works, but it does not use configurable-http-proxy (traeffik instead), which is what we are used to using as well as what the jupyterhub docker images use. Ended up creating this PR https://github.com/jupyterhub/the-littlest-jupyterhub/pull/554 due to umask problem that consumed a lot of time.

Thought to upgrade to jupyterhub 1.1, but it is broken:

```sh
docker run -it --rm -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub:1.1.0 jupyterhub
```

yields:

```txt
^[[31m[E 2020-04-23 01:30:07.052 JupyterHub web:1788]^[(B^[[m Uncaught exception GET /hub/login (::ffff:10.10.10.1)
    HTTPServerRequest(protocol='http', host='v.radia.run:8000', method='GET', uri='/hub/login', version='HTTP/1.1', remote_ip='::ffff:10.10.10.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 135, in get
        self.finish(self._render(username=username))
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 102, in _render
        {'next': self.get_argument('next', '')},
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1119, in render_template
        template = self.get_template(name)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1113, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 408, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: login.html
```

Docker image1.2 works, but it is a dev version, and there's not an official release jupyterhub to match that so we'd have to build beamsim-jupyter (which has to have jupyterhub installed).

I fixed one issue in the above by setting data_file_path, but style sheets weren't generated. 

I may need to install jupyterhub in our fedora image with pyenv. This would decouple from build issues they have with their Docker images, but require more configuration. I'll look at that tomorrow.

**Comment by robnagler** [comment]
I have the notebook server running within a Fedora install of jupyterhub. https://github.com/jupyterhub/jupyterhub/issues/2756 is related. I modified jupyter_notebook_config.py to:

```py
c.NotebookApp.base_url = '/user/vagrant'
```

This is without an nginx proxy. There might be a default base_url being set by default incorrectly.

**Comment by robnagler** [comment]
Figured out all the pieces. We need to call jupyterhub-singleuser (again) to wrap the notebook startup. 

Need to pass `--NotebookApp.default_url=/lab` to jupyterhub-singleuser so that it starts properly.

Need to update rsconf: https://github.com/radiasoft/rsconf/issues/106

**Comment by robnagler** [comment]
See https://github.com/jupyterlab/jupyterlab/issues/7067#issuecomment-619125454

**Comment by robnagler** [comment]
Fix
